In [2]:
import tensorflow as tf

In [8]:
tf.random.uniform(shape= (3, 2), seed= 42)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.94573236, 0.09348297],
       [0.5199989 , 0.44088244],
       [0.820037  , 0.35246098]], dtype=float32)>

In [22]:
tf.random.set_seed(42)
tf.random.uniform(shape= (3, 2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.6645621 , 0.44100678],
       [0.3528825 , 0.46448255],
       [0.03366041, 0.68467236]], dtype=float32)>

In [31]:
tf.random.set_seed(42)
tf.random.uniform(shape= (3, 2), seed= 42)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.4163028 , 0.26858163],
       [0.47968316, 0.36457133],
       [0.95471144, 0.9418646 ]], dtype=float32)>

CONCLUSION: IF WE SET ONLY THE OPERATIONAL SEED, THEN tf PICKS VALUES WITHIN THAT SEED, i.e. IT WILL KEEP CHANGING THE VALUES WHEN WE RE-RUN THE CELL. IF WE SET A GLOBAL SEED, IT SETS FIXED VALUES FROM THAT GLOBAL SEED. AND, IF WE SET GLOBAL + OPERATIONAL SEED, IT SETS A VALUE USING THE BOTH OF THEM.