In [18]:
import tensorflow as tf
import numpy as np
tf.__version__

'2.15.0'

In [2]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [3]:
#Scalar
scalar = tf.constant(7)
scalar

In [4]:
#Vector
vector = tf.constant([8, 8])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([8, 8], dtype=int32)>

In [5]:
#Matrix
matrix = tf.constant([[10, 7], [14, 17]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [14, 17]], dtype=int32)>

In [6]:
#Tensor
tensor = tf.constant([[[10, 7], [15, 12]], [[20, 22], [35, 8]]])
tensor

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [15, 12]],

       [[20, 22],
        [35,  8]]], dtype=int32)>

In [9]:
#Shape
print(scalar.shape)
#Rank
print(tf.rank(scalar))
#Size
print(tf.size(scalar))

()
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)


In [13]:
#Shape
print(vector.shape)
#Rank
print(tf.rank(vector))
#Size
print(tf.size(vector))

(2,)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


In [15]:
#Shape
print(matrix.shape)
#Rank
print(tf.rank(matrix))
#Size
print(tf.size(matrix))

(2, 2)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)


In [16]:
#Shape
print(tensor.shape)
#Rank
print(tf.rank(tensor))
#Size
print(tf.size(tensor))

(2, 2, 2)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)


In [34]:
tf.random.set_seed(42)

tensor_1 = tf.random.uniform(shape= [5, 300], minval= 0, maxval= 1)
tensor_1

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.6645621 , 0.44100678, 0.3528825 , ..., 0.31410468, 0.7593535 ,
        0.03699052],
       [0.532024  , 0.29129946, 0.10571766, ..., 0.54052293, 0.31425726,
        0.2200619 ],
       [0.08404207, 0.03614604, 0.97732127, ..., 0.21516645, 0.9786098 ,
        0.00726748],
       [0.7396945 , 0.6653172 , 0.0787828 , ..., 0.7117733 , 0.07013571,
        0.9409125 ],
       [0.15861344, 0.12024033, 0.27218235, ..., 0.8824879 , 0.1432488 ,
        0.44135118]], dtype=float32)>

In [35]:
tensor_2 = tf.random.uniform(shape= [5, 300], minval= 0, maxval= 1)
tensor_2

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.68789124, 0.48447883, 0.9309944 , ..., 0.6920762 , 0.33180213,
        0.9212563 ],
       [0.27369928, 0.10631859, 0.6218617 , ..., 0.4382149 , 0.30427706,
        0.51477313],
       [0.00920248, 0.37280262, 0.8177401 , ..., 0.56786287, 0.49201214,
        0.9892651 ],
       [0.88608265, 0.08672249, 0.12160683, ..., 0.91770685, 0.72545695,
        0.8280058 ],
       [0.36690474, 0.9200133 , 0.9646884 , ..., 0.69012   , 0.7137332 ,
        0.2584542 ]], dtype=float32)>

In [36]:
tf.linalg.matmul(tensor_1, tf.transpose(tensor_2))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[80.33342 , 73.40498 , 77.15965 , 73.98369 , 80.90055 ],
       [75.146355, 68.80439 , 74.24303 , 71.8418  , 75.60204 ],
       [79.7594  , 75.64456 , 77.79758 , 74.74876 , 80.55982 ],
       [75.08526 , 69.06409 , 74.30775 , 72.27616 , 76.05669 ],
       [85.05688 , 74.26627 , 78.00687 , 74.88679 , 83.134155]],
      dtype=float32)>

In [37]:
tf.tensordot(tensor_1, tf.transpose(tensor_2), axes= 1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[80.33342 , 73.40498 , 77.15965 , 73.98369 , 80.90055 ],
       [75.146355, 68.80439 , 74.24303 , 71.8418  , 75.60204 ],
       [79.7594  , 75.64456 , 77.79758 , 74.74876 , 80.55982 ],
       [75.08526 , 69.06409 , 74.30775 , 72.27616 , 76.05669 ],
       [85.05688 , 74.26627 , 78.00687 , 74.88679 , 83.134155]],
      dtype=float32)>

In [38]:
tensor_3 = tf.random.uniform(shape= [224, 224, 3], minval= 0, maxval= 1)
tensor_3

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.7413678 , 0.62854624, 0.01738465],
        [0.3431449 , 0.51063764, 0.3777541 ],
        [0.07321596, 0.02137029, 0.2871771 ],
        ...,
        [0.98953485, 0.45382905, 0.2006687 ],
        [0.6295223 , 0.4937899 , 0.01816809],
        [0.95386636, 0.11542463, 0.85691285]],

       [[0.78435016, 0.7826872 , 0.87936425],
        [0.24906898, 0.3207239 , 0.10955775],
        [0.543224  , 0.7151396 , 0.40334642],
        ...,
        [0.2445668 , 0.01746976, 0.9036933 ],
        [0.02975535, 0.592268  , 0.9877522 ],
        [0.36701274, 0.33112562, 0.5638567 ]],

       [[0.15829337, 0.7288823 , 0.3366307 ],
        [0.70792687, 0.16910625, 0.9429966 ],
        [0.10120225, 0.5919596 , 0.8687303 ],
        ...,
        [0.28134012, 0.10011208, 0.37038183],
        [0.77874243, 0.05421627, 0.4664607 ],
        [0.2549187 , 0.7968637 , 0.83405185]],

       ...,

       [[0.32922816, 0.06343532, 0.23936498],
        [0.42

In [39]:
tf.reduce_min(tensor_3)

<tf.Tensor: shape=(), dtype=float32, numpy=2.3841858e-07>

In [40]:
tf.reduce_max(tensor_3)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9999918>

In [41]:
tensor_4 = tf.random.uniform(shape= [1, 224, 224, 3], minval= 0, maxval= 1)

squeezed_tensor_4 = tf.squeeze(tensor_4)
squeezed_tensor_4

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[7.4023080e-01, 3.3938193e-01, 5.6925058e-01],
        [4.4811392e-01, 2.9285502e-01, 4.2600560e-01],
        [6.2890387e-01, 6.9106102e-01, 3.0925727e-01],
        ...,
        [9.1063976e-04, 6.9863999e-01, 1.7180574e-01],
        [6.7542684e-01, 8.3492923e-01, 3.9038682e-01],
        [2.3664141e-01, 6.2239432e-01, 1.0117912e-01]],

       [[9.7064960e-01, 5.4594779e-01, 7.6819682e-01],
        [2.6893330e-01, 2.6959443e-01, 2.8982997e-01],
        [2.9215467e-01, 1.7108858e-01, 6.5597153e-01],
        ...,
        [9.5621395e-01, 5.4591870e-01, 5.3843534e-01],
        [9.8861516e-01, 1.5786767e-01, 6.1375093e-01],
        [7.2668612e-01, 6.1637163e-03, 1.6534305e-01]],

       [[6.4095867e-01, 7.6697862e-01, 3.0138540e-01],
        [1.5474892e-01, 1.7183411e-01, 2.7192724e-01],
        [3.1211805e-01, 6.1451709e-01, 4.3001354e-01],
        ...,
        [8.4168065e-01, 5.0247252e-01, 2.8834987e-01],
        [3.3173549e-01

In [42]:
tensor_5 = tf.constant([1, 2, 3, 5, -2.5, 0.333, 9, 0.000001, -100, 4])
tensor_5

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([ 1.00e+00,  2.00e+00,  3.00e+00,  5.00e+00, -2.50e+00,  3.33e-01,
        9.00e+00,  1.00e-06, -1.00e+02,  4.00e+00], dtype=float32)>

In [43]:
tf.argmax(tensor_5)

<tf.Tensor: shape=(), dtype=int64, numpy=6>

In [44]:
tf.argmin(tensor_5)

<tf.Tensor: shape=(), dtype=int64, numpy=8>

In [46]:
tf.one_hot(tf.cast(tensor_5, dtype= tf.int32), depth= 4)

<tf.Tensor: shape=(10, 4), dtype=float32, numpy=
array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>