## Introduction to tensors using TensorFlow

* TensorFlow tf.function() is a way to speed up regular Python functions
* Used with GPUs/TPUs for fast numerical computing. That's its main purpose.

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.17.1


## Creating Tensors with tf.constant()

* Mostly won't be creating too many Tensors on our own
* Tf has a lot of modules that can read in data sources (e.g. images) and convert them to Tensors (depending on code we write)
* Later on, Neural Network model will process Tesnsors for us

In [ ]:
help(tf.constant)

Help on function constant in module tensorflow.python.framework.constant_op:

constant(value, dtype=None, shape=None, name='Const') -> Union[tensorflow.python.framework.ops.Operation, tensorflow.python.framework.ops._EagerTensorBase]
    Creates a constant tensor from a tensor-like object.
    
    Note: All eager `tf.Tensor` values are immutable (in contrast to
    `tf.Variable`). There is nothing especially _constant_ about the value
    returned from `tf.constant`. This function is not fundamentally different from
    `tf.convert_to_tensor`. The name `tf.constant` comes from the `value` being
    embedded in a `Const` node in the `tf.Graph`. `tf.constant` is useful
    for asserting that the value can be embedded that way.
    
    If the argument `dtype` is not specified, then the type is inferred from
    the type of `value`.
    
    >>> # Constant 1-D Tensor from a python list.
    >>> tf.constant([1, 2, 3, 4, 5, 6])
    <tf.Tensor: shape=(6,), dtype=int32,
        numpy=array([

In [ ]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

Check the dimensions of a tensor. ndim is the number of dimensions

In [ ]:
scalar.ndim

0

In [ ]:
# Create a vector

vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
#Create a matrix

matrix = tf.constant([[10, 7],
                      [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
#Create another matrix
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [8., 9.]], dtype= 'float16') #Can also use tf.float16, but that will be used without the quotes
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
#Creating a Tensor
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

## Creating Tensors with tf.variable()
* It creates a changeable tensor

In [ ]:
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])

changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
changeable_tensor[0] = 7
changeable_tensor

TypeError: 'ResourceVariable' object does not support item assignment

In [ ]:
# We can't directly assign avalue to a position with []. Let's use .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
#What if we tried to change the unchangeable tensor
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

NOTE: SEEMS LIKE THE tf.constant() TENSORS ARE SIMILAR TO SETS/TUPLES IN REGULAR PYTHON, IN THAT THEY'RE UNCHANGEABLE. ON THE OTHER HAND tf.Variable() TENSORS ARE LIKE LISTS, IN THAT THEY CAN BE FREELY UPDATED.

## Creating Random Tensors
* They are of arbitrary size and filled with random numbers
* They can be used as an initial Tensor that'll be then tweaked with more pertinent values as the model keeps updating.

In [ ]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape= (3, 2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

In [ ]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape= (3, 2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

In [ ]:
random_1 == random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

## Shuffle the order of elements in a tensor
* Basically similar to the concept of shuffling the rows in a train-test split
* For our shuffled tensors need to have the same shuffle state, we need to assign both a global-level random seed and operation-level random seed.

In [ ]:
not_suffled = tf.constant([[10, 7],
                          [3, 4],
                          [2, 5]])
not_suffled.ndim

2

In [ ]:
#Shuffling the tensor
tf.random.shuffle(not_suffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
#Now, if we only set the seed within the args for tf.random.shuffle(), it'll still change the order on every refresh.
#Instead, we need to set seed manually outside it

tf.random.set_seed(42) #global seed
tf.random.shuffle(not_suffled, seed= 42) #operation seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

## Other way to make tensors
* Tensorflow has its own built-in functions that are similar to Numpy, such as tf.ones being the same as np.ones
* `tf.ones()`
* `tf.zeros()`

In [ ]:
#Create a tensor or all ones
tf.ones(shape= [10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
#Create a tensor of all zeroes
tf.zeros(shape= [10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

## Turning NumPy arrays into Tensorflow tensors
* The main difference between NumPy arrays and Tensorflow tensors is that tensors can be run on GPUs (offer much faster numerical computing).

In [ ]:
import numpy as np

In [ ]:
numpy_A = np.arange(1, 25, dtype= np.int32)
numpy_A

#X = tf.constant(some_matrix) #Capitalize the name for matrix or tensor
#y = tf.constant(vector) #lower caps for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpy_A, shape= (2, 3, 4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [ ]:
type(A)

tensorflow.python.framework.ops.EagerTensor

In [ ]:
B = tf.constant(numpy_A, shape= (2, 3, 2, 2))
B

<tf.Tensor: shape=(2, 3, 2, 2), dtype=int32, numpy=
array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]],


       [[[13, 14],
         [15, 16]],

        [[17, 18],
         [19, 20]],

        [[21, 22],
         [23, 24]]]], dtype=int32)>

In [ ]:
A.ndim, B.ndim

(3, 4)

## Getting information from Tensors
* We may need to get more information from our tensors, i.e. their attributes, like
 * Shape
 *  Rank
 * Axis/dimension
 * Size

In [ ]:
#Cerate a rank 4 tensor (i.e. 4 dimensions)
rank_4_tensor = tf.zeros(shape= [2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
#Get various attributes of tensors
print("Datatype of every element: ", rank_4_tensor.dtype)
print("Number of dimensions (rank): ", rank_4_tensor.ndim)
print("Shape of tensor: ", rank_4_tensor.shape)
print("Elements along 0 axis: ", rank_4_tensor.shape[0])
print("Elements along the last axis: ", rank_4_tensor.shape[-1])
print("The total number of elements in our tensor: ", tf.size(rank_4_tensor))
print("The total number of elements in our tensor: ", tf.size(rank_4_tensor).numpy()) #For a lot of the tensorflow attributes, we can attach .numpy() at the end to get just value

Datatype of every element:  <dtype: 'float32'>
Number of dimensions (rank):  4
Shape of tensor:  (2, 3, 4, 5)
Elements along 0 axis:  2
Elements along the last axis:  5
The total number of elements in our tensor:  tf.Tensor(120, shape=(), dtype=int32)
The total number of elements in our tensor:  120


## Indexing Tensors
Tensors can be indexed like lists, as we've seen before.

In [ ]:
#Getting the first two elements of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
B, B.ndim

(<tf.Tensor: shape=(2, 3, 2, 2), dtype=int32, numpy=
 array([[[[ 1,  2],
          [ 3,  4]],
 
         [[ 5,  6],
          [ 7,  8]],
 
         [[ 9, 10],
          [11, 12]]],
 
 
        [[[13, 14],
          [15, 16]],
 
         [[17, 18],
          [19, 20]],
 
         [[21, 22],
          [23, 24]]]], dtype=int32)>,
 4)

In [ ]:
B[:2, :2, :1, :]

<tf.Tensor: shape=(2, 2, 1, 2), dtype=int32, numpy=
array([[[[ 1,  2]],

        [[ 5,  6]]],


       [[[13, 14]],

        [[17, 18]]]], dtype=int32)>

From the above code we can see that each list slice is dependent on the list slice before. Since we start with :1, it'll only consider the first element of the Tensor, and then upto the second element (:2) and so on and so forth.

In [ ]:
# Get the first element from each dimension from each index except for the final
# one
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape

TensorShape([2, 3, 4, 5])

In [ ]:
rank_4_tensor[:1, :1, :, :1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[:1, :, :1, :1]

<tf.Tensor: shape=(1, 3, 1, 1), dtype=float32, numpy=
array([[[[0.]],

        [[0.]],

        [[0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[:, :1, :1, :1]

<tf.Tensor: shape=(2, 1, 1, 1), dtype=float32, numpy=
array([[[[0.]]],


       [[[0.]]]], dtype=float32)>

In [ ]:
#Create a rank 2 Tensor(2 dim)
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [ ]:
#Get the last item of each row
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [ ]:
#Add an extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

The '...' signifies that we add a new axis at the end of the existing dimensions. So, instead of writing [:, :, tf.newaxis], we can simply shorten that by using '...'.

In [ ]:
#Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis= -1) #-1 symbolizes that we expand on the last axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
#Expand on axis 0
tf.expand_dims(rank_2_tensor, axis= 0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

## Manipulating Tensors (Tensor Operations)
* ** Basic Operations **
* `+`, `-`, `*`, `/`

In [ ]:
#Add values to a tensor using `+`
tensor = tf.constant([[10, 7], [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
#Multiplication
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
#Subtraction
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [ ]:
#Division
tensor / 10

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1. , 0.7],
       [0.3, 0.4]])>

In [ ]:
#There are built-in functions too for tensorflow
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

NOTE: The tensorflow versions, i.e. tf.multiply, tf.add, etc., are better optimized to run on GPUs and will work faster.