#Tensor Fundamentals (Contd.)

In [1]:
import tensorflow as tf
import numpy as np

## Tensor Datatypes

In [2]:
# Create tensor with default datatype
B = tf.constant([1.7, 7.4])
B, B.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>,
 tf.float32)

In [3]:
C = tf.constant([7, 10])
C, C.dtype

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>,
 tf.int32)

In [4]:
#Change from float32 to float16, i.e. reduced precision
D = tf.cast(B, dtype= tf.float16)
D, D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

In [5]:
#Change from int32 to float32
E = tf.cast(C, dtype= tf.float32)
E, E.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>,
 tf.float32)

In [6]:
E_float16 = tf.cast(E, dtype= tf.float16)
E_float16, E_float16.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 7., 10.], dtype=float16)>,
 tf.float16)

## Aggregating Tensors

In [7]:
#Getting the absolute values
D = tf.constant([-7, -10])
D, tf.abs(D)

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>)

Forms of Tensor Aggregation:
* Get the min
* Get the max
* Get the mean
* Get the sum

In [8]:
#Create random tensor between 0 to 100 with size= 50
E = tf.constant(np.random.randint(0, 100, size= 50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([52, 80,  1, 32, 26, 35, 62,  5, 21, 18, 87,  3, 12, 63,  4, 24, 40,
       20, 74, 89, 83, 14, 41, 34, 90, 85, 16, 28, 24, 98, 74, 62, 93, 81,
       29, 67, 59,  7, 51, 30, 85, 52, 80, 81, 66, 99, 10, 53, 89, 58])>

In [9]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [10]:
#Find min
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [11]:
#Find max
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [12]:
#Find mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=49>

In [13]:
#find sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2487>

**Exercise**: Finding the variance and standard deviation of our `E Tensor`

In [14]:
#Standard Deviation
tf.math.reduce_std(tf.cast(E, dtype= tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=30.079767>

In [15]:
#Variance
tf.math.reduce_variance(tf.cast(E, dtype= 'float32'))

<tf.Tensor: shape=(), dtype=float32, numpy=904.7924>

In [16]:
import tensorflow_probability as tfp

In [17]:
#Alternate Standard Deviation
tfp.stats.stddev(tf.cast(E, dtype= tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=30.079767>

In [18]:
#Alternate Variance
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=905>

## Finding the Positional Max and Min
* For ex., we use this to isolate our required classification label, i.e. if the output row 0 has a max value for the column dedicated to 'Ramen', we know that that specific image corresponds to Ramen

In [19]:
#Create new tensor
tf.random.set_seed(42)
F = tf.random.uniform(shape= [50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [20]:
#Fining Positional Max (Arg Max)
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [21]:
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [22]:
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [23]:
#Finding the Positional Min (Arg Min)
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [24]:
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [25]:
tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [26]:
#Finding positional max for 2-dimensional tensor
tf.reshape(F, shape= (10, 5)), tf.reshape(F, shape= (10, 5)).ndim

(<tf.Tensor: shape=(10, 5), dtype=float32, numpy=
 array([[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041],
        [0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686],
        [0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ],
        [0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ],
        [0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ],
        [0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173],
        [0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ],
        [0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ],
        [0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943],
        [0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]],
       dtype=float32)>,
 2)

In [27]:
tf.argmax(tf.reshape(F, shape= (10, 5))) #If we run this, it'll searches along the columns

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([6, 7, 8, 5, 8])>

In [28]:
tf.argmax(tf.reshape(F, shape= (10, 5)), axis= 1) #If we run this, it'll searches along the rows

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([0, 2, 1, 0, 0, 3, 0, 2, 2, 3])>

## Squeezing a Tensor
* This refers to removing all single dimensions
* If a tensor has multiple single dimensions, i.e. multiple `[]` on it, this extract the dimension with multiple values from inside it.

In [32]:
#Create a Tensor
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape= [50]), shape= (1, 1, 1, 50))
G

<tf.Tensor: shape=(1, 1, 1, 50), dtype=float32, numpy=
array([[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
          0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
          0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
          0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
          0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
          0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
          0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
          0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
          0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
          0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]],
      dtype=float32)>

In [34]:
G.shape

TensorShape([1, 1, 1, 50])

In [35]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

## One-hot Encoding a Tensor

In [40]:
#Create a list of indices
some_list = [0, 1, 2, 3] #Maybe these can be red, green, blue, purple

#We hot-hot encode our list
tf.one_hot(some_list, depth= 4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

NOTE: For the above one-hot encoding, we can use depth= 3 to make it work too. In the case of depth= 3, it'll work similar to pd.get_dummies() with `drop_first= True`

In [41]:
#Specify custom values for one-hot encoding
tf.one_hot(some_list, depth= 4, on_value= 'ON', off_value= 'OFF')

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'ON', b'OFF', b'OFF', b'OFF'],
       [b'OFF', b'ON', b'OFF', b'OFF'],
       [b'OFF', b'OFF', b'ON', b'OFF'],
       [b'OFF', b'OFF', b'OFF', b'ON']], dtype=object)>

## More Math Operations
* Squaring
* Log
* Square Root

In [43]:
#Creae a new Tensor
H = tf.range(1, 10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

### Squaring

In [44]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

###Log

In [47]:
tf.math.log(tf.cast(H, dtype= tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Square Root

In [49]:
tf.math.sqrt(tf.cast(H, dtype= tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.2360678, 2.4494896,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>